project:
  type: book
  render:
  - index.qmd
  - parallel.qmd
  output-dir: docs
number-depth: 0
book:
  title: Statistical Computing Practicals
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    search: true
    background: light
  chapters:
  - index.qmd
  - parallel.qmd
format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    toc-location: left
    
  



